Repository moonstar0331/fintech-loan, pull requests merged in 2023-07, with the labels that each got.

#2 대출 상담 도메인 정의
  src/main/java/com/loan/loan/domain/Counsel.java
Labels: documentation

#3 Feat: 대출 상담 등록 기능 구현
  build.gradle
  src/main/java/com/loan/loan/controller/CounselController.java
  src/main/java/com/loan/loan/dto/CounselDTO.java
  src/main/java/com/loan/loan/repository/CounselRepository.java
  src/main/java/com/loan/loan/service/CounselService.java
  src/main/java/com/loan/loan/service/CounselServiceImpl.java
  src/main/resources/application.yml
  src/test/java/com/loan/loan/service/CounselServiceTest.java
Labels: documentation, enhancement

#4 Feat: 대출 상담 조회 기능 구현
  src/main/java/com/loan/loan/controller/CounselController.java
  src/main/java/com/loan/loan/service/CounselService.java
  src/main/java/com/loan/loan/service/CounselServiceImpl.java
  src/test/java/com/loan/loan/service/CounselServiceTest.java
Labels: enhancement

#5 Feat: 대출 상담 정보 수정 기능 구현
  src/main/java/com/loan/loan/controller/CounselController.java
  src/main/java/com/loan/loan/service/CounselService.java
  src/main/java/com/loan/loan/service/CounselServiceImpl.java
  src/test/java/com/loan/loan/service/CounselServiceTest.java
Labels: enhancement

#6 Feat: 대출 상담 삭제 기능 구현
  src/main/java/com/loan/loan/controller/CounselController.java
  src/main/java/com/loan/loan/service/CounselService.java
  src/main/java/com/loan/loan/service/CounselServiceImpl.java
  src/test/java/com/loan/loan/service/CounselServiceTest.java
Labels: enhancement

#7 Feat: 대출 신청 도메인 테이블 정의
  src/main/java/com/loan/loan/domain/Application.java
Labels: enhancement

#9 Feat: 대출 신청 조회 기능 구현
  src/main/java/com/loan/loan/controller/ApplicationController.java
  src/main/java/com/loan/loan/service/ApplicationService.java
  src/main/java/com/loan/loan/service/ApplicationServiceImpl.java
  src/test/java/com/loan/loan/service/ApplicationServiceTest.java
Labels: enhancement

#10 Feat: 대출 신청 삭제 기능 구현
  src/main/java/com/loan/loan/controller/ApplicationController.java
  src/main/java/com/loan/loan/service/ApplicationService.java
  src/main/java/com/loan/loan/service/ApplicationServiceImpl.java
  src/test/java/com/loan/loan/service/ApplicationServiceTest.java
Labels: enhancement

#12 Feat: 이용 약관 도메인 테이블 작성
  src/main/java/com/loan/loan/domain/Terms.java
Labels: enhancement

#13 Feat : 이용 약관 등록 기능 구현
  src/main/java/com/loan/loan/controller/CounselController.java
  src/main/java/com/loan/loan/controller/TermsController.java
  src/main/java/com/loan/loan/dto/TermsDTO.java
  src/main/java/com/loan/loan/repository/TermsRepository.java
  src/main/java/com/loan/loan/service/TermsService.java
  src/main/java/com/loan/loan/service/TermsServiceImpl.java
  src/test/java/com/loan/loan/service/TermsServiceTest.java
Labels: enhancement

#14 Feat : 이용 약관 전체 조회 기능 구현
  src/main/java/com/loan/loan/controller/TermsController.java
  src/main/java/com/loan/loan/service/TermsService.java
  src/main/java/com/loan/loan/service/TermsServiceImpl.java
  src/test/java/com/loan/loan/service/TermsServiceTest.java
Labels: enhancement

#15 Feat : 대출 신청 약관 동의 기능 구현
  src/main/java/com/loan/loan/controller/ApplicationController.java
  src/main/java/com/loan/loan/domain/AcceptTerms.java
  src/main/java/com/loan/loan/dto/ApplicationDTO.java
  src/main/java/com/loan/loan/repository/AcceptTermsRepository.java
  src/main/java/com/loan/loan/service/ApplicationService.java
  src/main/java/com/loan/loan/service/ApplicationServiceImpl.java
  src/test/java/com/loan/loan/service/ApplicationServiceTest.java
Labels: enhancement

#17 Feat : 대출 신청 서류 등록 기능 구현
  src/main/java/com/loan/loan/controller/ApplicationController.java
  src/main/java/com/loan/loan/service/FileStorageService.java
  src/main/java/com/loan/loan/service/FileStorageServiceImpl.java
  src/main/resources/application.yml
Labels: enhancement

#18 Feat : 대출 신청 서류 조회 기능 구현
  src/main/java/com/loan/loan/controller/ApplicationController.java
  src/main/java/com/loan/loan/dto/FileDTO.java
  src/main/java/com/loan/loan/exception/ResultType.java
  src/main/java/com/loan/loan/service/FileStorageService.java
  src/main/java/com/loan/loan/service/FileStorageServiceImpl.java
Labels: enhancement

#19 Feat : 대출 신청 서류 삭제 기능 구현
  src/main/java/com/loan/loan/controller/ApplicationController.java
  src/main/java/com/loan/loan/service/FileStorageService.java
  src/main/java/com/loan/loan/service/FileStorageServiceImpl.java
Labels: enhancement

#20 Feat: 대출 신청 서류 매핑 기능 구현
  src/main/java/com/loan/loan/controller/ApplicationController.java
  src/main/java/com/loan/loan/service/FileStorageService.java
  src/main/java/com/loan/loan/service/FileStorageServiceImpl.java
Labels: enhancement

#21 Feat : 대출 신청 서류 기능 구현
  src/main/java/com/loan/loan/controller/ApplicationController.java
  src/main/java/com/loan/loan/dto/FileDTO.java
  src/main/java/com/loan/loan/exception/ResultType.java
  src/main/java/com/loan/loan/service/FileStorageService.java
  src/main/java/com/loan/loan/service/FileStorageServiceImpl.java
  src/main/resources/application.yml
Labels: enhancement

#22 Feat: 대출 심사 도메인 테이블 정의 및 대출 신청 도메인 테이블 수정
  src/main/java/com/loan/loan/domain/Application.java
  src/main/java/com/loan/loan/domain/Judgment.java
Labels: enhancement

#23 Feat : 대출 심사 등록 기능 구현
  src/main/java/com/loan/loan/controller/JudgementController.java
  src/main/java/com/loan/loan/dto/JudgmentDTO.java
  src/main/java/com/loan/loan/repository/JudgementRepository.java
  src/main/java/com/loan/loan/service/JudgementServiceImpl.java
  src/main/java/com/loan/loan/service/JudgmentService.java
  src/test/java/com/loan/loan/service/JudgementServiceTest.java
Labels: enhancement

#24 Feat : 대출 심사 조회 기능 구현
  src/main/java/com/loan/loan/controller/JudgementController.java
  src/main/java/com/loan/loan/repository/JudgementRepository.java
  src/main/java/com/loan/loan/service/JudgementServiceImpl.java
  src/main/java/com/loan/loan/service/JudgmentService.java
  src/test/java/com/loan/loan/service/JudgementServiceTest.java
Labels: enhancement

#25 Feat : 대출 심사 정보 수정 기능 구현
  src/main/java/com/loan/loan/controller/JudgementController.java
  src/main/java/com/loan/loan/service/JudgementServiceImpl.java
  src/main/java/com/loan/loan/service/JudgmentService.java
  src/test/java/com/loan/loan/service/JudgementServiceTest.java
Labels: enhancement

#26 Feat : 대출 심사 삭제 기능 구현
  src/main/java/com/loan/loan/controller/JudgementController.java
  src/main/java/com/loan/loan/service/JudgementServiceImpl.java
  src/main/java/com/loan/loan/service/JudgmentService.java
  src/test/java/com/loan/loan/service/JudgementServiceTest.java
Labels: enhancement

#27 Feat : 대출 심사 금액 부여 기능 구현
  src/main/java/com/loan/loan/controller/JudgementController.java
  src/main/java/com/loan/loan/dto/ApplicationDTO.java
  src/main/java/com/loan/loan/service/JudgementServiceImpl.java
  src/main/java/com/loan/loan/service/JudgmentService.java
  src/test/java/com/loan/loan/service/JudgementServiceTest.java
Labels: enhancement

#28 Feat : 대출 심사 기능 개발
  src/main/java/com/loan/loan/controller/JudgementController.java
  src/main/java/com/loan/loan/domain/Application.java
  src/main/java/com/loan/loan/domain/Judgment.java
  src/main/java/com/loan/loan/dto/ApplicationDTO.java
  src/main/java/com/loan/loan/dto/JudgmentDTO.java
  src/main/java/com/loan/loan/repository/JudgementRepository.java
  src/main/java/com/loan/loan/service/JudgementServiceImpl.java
  src/main/java/com/loan/loan/service/JudgmentService.java
  src/test/java/com/loan/loan/service/JudgementServiceTest.java
Labels: enhancement

#29 Feat : 대출 집행 기능 개발을 위한 도메인 테이블 정의
  src/main/java/com/loan/loan/domain/Balance.java
  src/main/java/com/loan/loan/domain/Entry.java
Labels: enhancement

#30 Feat : 대출 계약 기능 구현
  src/main/java/com/loan/loan/controller/ApplicationController.java
  src/main/java/com/loan/loan/domain/Application.java
  src/main/java/com/loan/loan/dto/ApplicationDTO.java
  src/main/java/com/loan/loan/service/ApplicationService.java
  src/main/java/com/loan/loan/service/ApplicationServiceImpl.java
Labels: enhancement

#31 Feat : 대출 집행 기능 개발
  src/main/java/com/loan/loan/controller/ApplicationController.java
  src/main/java/com/loan/loan/controller/InternalController.java
  src/main/java/com/loan/loan/domain/Application.java
  src/main/java/com/loan/loan/domain/Balance.java
  src/main/java/com/loan/loan/domain/Entry.java
  src/main/java/com/loan/loan/dto/ApplicationDTO.java
  src/main/java/com/loan/loan/dto/BalanceDTO.java
  src/main/java/com/loan/loan/dto/EntryDTO.java
  src/main/java/com/loan/loan/repository/BalanceRepository.java
  src/main/java/com/loan/loan/repository/EntryRepository.java
  src/main/java/com/loan/loan/service/ApplicationService.java
  src/main/java/com/loan/loan/service/ApplicationServiceImpl.java
  src/main/java/com/loan/loan/service/BalanceService.java
  src/main/java/com/loan/loan/service/BalanceServiceImpl.java
  src/main/java/com/loan/loan/service/EntryService.java
  src/main/java/com/loan/loan/service/EntryServiceImpl.java
Labels: enhancement

#32 Feat: 대출 상환 도메인 테이블 정의
  src/main/java/com/loan/loan/domain/Repayment.java
Labels: enhancement

#33 Feat : 대출 상환 등록 기능 구현
  src/main/java/com/loan/loan/controller/InternalController.java
  src/main/java/com/loan/loan/dto/BalanceDTO.java
  src/main/java/com/loan/loan/dto/RepaymentDTO.java
  src/main/java/com/loan/loan/repository/RepaymentRepository.java
  src/main/java/com/loan/loan/service/BalanceService.java
  src/main/java/com/loan/loan/service/BalanceServiceImpl.java
  src/main/java/com/loan/loan/service/RepaymentService.java
  src/main/java/com/loan/loan/service/RepaymentServiceImpl.java
Labels: enhancement

#34 Feat : 대출 상환 전체 조회 기능 구현
  src/main/java/com/loan/loan/controller/InternalController.java
  src/main/java/com/loan/loan/dto/RepaymentDTO.java
  src/main/java/com/loan/loan/repository/RepaymentRepository.java
  src/main/java/com/loan/loan/service/RepaymentService.java
  src/main/java/com/loan/loan/service/RepaymentServiceImpl.java
Labels: enhancement

#36 Feat : 대출 상환 삭제 기능 구현
  src/main/java/com/loan/loan/controller/InternalController.java
  src/main/java/com/loan/loan/service/RepaymentService.java
  src/main/java/com/loan/loan/service/RepaymentServiceImpl.java
Labels: enhancement

#37 Feat : 대출 상환 기능 개발
  src/main/java/com/loan/loan/controller/InternalController.java
  src/main/java/com/loan/loan/domain/Repayment.java
  src/main/java/com/loan/loan/dto/BalanceDTO.java
  src/main/java/com/loan/loan/dto/RepaymentDTO.java
  src/main/java/com/loan/loan/repository/RepaymentRepository.java
  src/main/java/com/loan/loan/service/BalanceService.java
  src/main/java/com/loan/loan/service/BalanceServiceImpl.java
  src/main/java/com/loan/loan/service/RepaymentService.java
  src/main/java/com/loan/loan/service/RepaymentServiceImpl.java
Labels: enhancement
